name: 5-minute-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:

  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        env:
          Authorization_Bearer : ${{ secrets.secrets.TASKAUTH}}
      
        run: |
          curl --request POST \
          --url 'https://decode.antibot.to/api/akamai/runtask' \
          --header 'Authorization: Bearer ${#Authorization_Bearer}'
