name: 5-minute-cron

on:
  push:
    branches:
     - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
      
        run: |
          curl --request POST \
          --url 'https://decode.antibot.to/api/akamai/runtask' \
          --header 'Authorization: ${{ secrets.TASKAUTH }}'
